In [ ]:
import pandas as pd

In [ ]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'London', 'Paris']
}

# 2. Create the DataFrame
df = pd.DataFrame(data)

In [ ]:
df

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

In [ ]:
data = {
    'EmployeeID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Name': ['John', 'Mary', 'David','Sarah','James','Grace','Peter','Linda','Michael','Susan'],
    'Department': ['IT', 'HR', 'Finance','IT','Sales','HR','Finance','Sales','IT','HR'],
    'Age': [25, 30, 28, 35, 26, 32, 29, 31, 27, 34],
    'Salary': [50000, 65000, 60000, 80000, 55000, 70000, 62000, 68000, 58000,75000],
    'Experience': [2 ,5, 3, 8, 2, 6, 4, 5, 3, 7],

}

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

   EmployeeID     Name Department  Age  Salary  Experience
0         101     John         IT   25   50000           2
1         102     Mary         HR   30   65000           5
2         103    David    Finance   28   60000           3
3         104    Sarah         IT   35   80000           8
4         105    James      Sales   26   55000           2
5         106    Grace         HR   32   70000           6
6         107    Peter    Finance   29   62000           4
7         108    Linda      Sales   31   68000           5
8         109  Michael         IT   27   58000           3
9         110    Susan         HR   34   75000           7

In [ ]:
df.head()

   EmployeeID   Name Department  Age  Salary  Experience
0         101   John         IT   25   50000           2
1         102   Mary         HR   30   65000           5
2         103  David    Finance   28   60000           3
3         104  Sarah         IT   35   80000           8
4         105  James      Sales   26   55000           2

In [ ]:
df.head(3)

   EmployeeID   Name Department  Age  Salary  Experience
0         101   John         IT   25   50000           2
1         102   Mary         HR   30   65000           5
2         103  David    Finance   28   60000           3

In [ ]:
df.tail()

   EmployeeID     Name Department  Age  Salary  Experience
5         106    Grace         HR   32   70000           6
6         107    Peter    Finance   29   62000           4
7         108    Linda      Sales   31   68000           5
8         109  Michael         IT   27   58000           3
9         110    Susan         HR   34   75000           7

In [ ]:
df.shape

(10, 6)

In [ ]:
df[['Name', 'City']]

      Name      City
0    Alice  New York
1      Bob    London
2  Charlie     Paris

In [ ]:
df.dtypes

Name    object
Age      int64
City    object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [ ]:
 df.describe()

        Age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

In [ ]:
df['Age']

0    25
1    30
2    35
Name: Age, dtype: int64

In [ ]:
df = pd.read_csv('/content/Employee.csv')

In [ ]:
df[['Age', 'Gender']]

      Age  Gender
0      34    Male
1      28  Female
2      38  Female
3      27    Male
4      24    Male
...   ...     ...
4648   26  Female
4649   37    Male
4650   27    Male
4651   30    Male
4652   33    Male

[4653 rows x 2 columns]

In [ ]:
df['Age'].min()

22

In [ ]:
df['Age'].max()

41

In [ ]:
df.to_csv('output.csv', index=False)

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/winemag-data-130k-v2.csv', engine='python', on_bad_lines='skip')

In [ ]:
df

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113464,113464,US,"Strawberry fruit defines this open, broad-flav...",Freedom Stand Sure Vineyard,89,29.0,Oregon,Eola-Amity Hills,Willamette Valley,Paul Gregutt,@paulgwine,Schultz 2014 Freedom Stand Sure Vineyard Pinot...,Pinot Noir,Schultz
113465,113465,US,"Fresh and enticing aromas of blackberry, raspb...",Roots,89,50.0,Virginia,Virginia,NaN,Carrie Dykes,NaN,Slater Run 2014 Roots Red (Virginia),Bordeaux-style Red Blend,Slater Run
113466,113466,US,"Consistent with the previous vintage, this com...",Orchard Block,89,70.0,Oregon,Dundee Hills,Willamette Valley,Paul Gregutt,@paulgwine,Sokol Blosser 2014 Orchard Block Pinot Noir (D...,Pinot Noir,Sokol Blosser
113467,113467,US,This full-bodied attractively dry wine has ver...,Ball & Chain,89,28.0,California,California,California Other,Jim Gordon,@gordone_cellars,Solitary Cellars 2014 Ball & Chain Red (Califo...,Red Blend,Solitary Cellars
113468,113468,US,"One of the more substantial examples of rosé, ...",NaN,89,16.0,California,Dunnigan Hills,Central Valley,Jim Gordon,@gordone_cellars,Tinto,None,None

In [ ]:
df.isna()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,False,False,False,False,False,True,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,False,True,True,False,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113464,False,False,False,False,False,False,False,False,False,False,False,False,False,False
113465,False,False,False,False,False,False,False,False,True,False,True,False,False,False
113466,False,False,False,False,False,False,False,False,False,False,False,False,False,False
113467,False,False,False,False,False,False,False,False,False,False,False,False,False,False
113468,False,False,False,True,False,False,False,False,False,False,False,False,True,True

In [ ]:
df.isnull()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,False,False,False,False,False,True,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,False,True,True,False,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113464,False,False,False,False,False,False,False,False,False,False,False,False,False,False
113465,False,False,False,False,False,False,False,False,True,False,True,False,False,False
113466,False,False,False,False,False,False,False,False,False,False,False,False,False,False
113467,False,False,False,False,False,False,False,False,False,False,False,False,False,False
113468,False,False,False,True,False,False,False,False,False,False,False,False,True,True

In [ ]:
df.isnull().sum()

Unnamed: 0                   0
country                     52
description                  0
designation              32701
points                       0
price                     7923
province                    52
region_1                 18597
region_2                 69584
taster_name              23039
taster_twitter_handle    27354
title                        0
variety                      2
winery                       1
dtype: int64

In [ ]:
df.isna().sum()

Unnamed: 0                   0
country                     52
description                  0
designation              32701
points                       0
price                     7923
province                    52
region_1                 18597
region_2                 69584
taster_name              23039
taster_twitter_handle    27354
title                        0
variety                      2
winery                       1
dtype: int64

In [ ]:
df.columns

Index(['Unnamed: 0', 'country', 'description', 'designation', 'points',
       'price', 'province', 'region_1', 'region_2', 'taster_name',
       'taster_twitter_handle', 'title', 'variety', 'winery'],
      dtype='object')

In [ ]:
df[['country','points','price']]

         country  points  price
0          Italy      87    NaN
1       Portugal      87   15.0
2             US      87   14.0
3             US      87   13.0
4             US      87   65.0
...          ...     ...    ...
113464        US      89   29.0
113465        US      89   50.0
113466        US      89   70.0
113467        US      89   28.0
113468        US      89   16.0

[113469 rows x 3 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113469 entries, 0 to 113468
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             113469 non-null  int64
 1   country                113417 non-null  object
 2   description            113469 non-null  object
 3   designation            80768 non-null   object
 4   points                 113469 non-null  int64
 5   price                  105546 non-null  float64
 6   province               113417 non-null  object
 7   region_1               94872 non-null   object
 8   region_2               43885 non-null   object
 9   taster_name            90430 non-null   object
 10  taster_twitter_handle  86115 non-null   object
 11  title                  113469 non-null  object
 12  variety                113467 non-null  object
 13  winery                 113468 non-null  object
dtypes: float64(1), int64(2), object(11)
memory usage: 12.1+ MB

In [ ]:
df.shape

(113469, 14)

In [ ]:
df['country'].unique()

array(['Italy', 'Portugal', 'US', 'Spain', 'France', 'Germany',
       'Argentina', 'Chile', 'Australia', 'Austria', 'South Africa',
       'New Zealand', 'Israel', 'Hungary', 'Greece', 'Romania', 'Mexico',
       'Canada', nan, 'Turkey', 'Czech Republic', 'Slovenia',
       'Luxembourg', 'Croatia', 'Georgia', 'Uruguay', 'England',
       'Lebanon', 'Serbia', 'Brazil', 'Moldova', 'Morocco', 'Peru',
       'India', 'Bulgaria', 'Cyprus', 'Armenia', 'Switzerland',
       'Bosnia and Herzegovina', 'Ukraine', 'Slovakia', 'Macedonia',
       'China', 'Egypt'], dtype=object)

In [ ]:
df['country'].nunique()

43

In [ ]:
df['country'].value_counts()

country
US                        47360
France                    19374
Italy                     17231
Spain                      5758
Portugal                   5005
Chile                      3905
Argentina                  3324
Austria                    2938
Australia                  2023
Germany                    1884
New Zealand                1246
South Africa               1237
Israel                      435
Greece                      395
Canada                      204
Hungary                     121
Bulgaria                    118
Romania                      96
Uruguay                      94
Turkey                       78
Georgia                      77
Slovenia                     72
England                      64
Croatia                      64
Mexico                       62
Brazil                       52
Moldova                      49
Lebanon                      31
Morocco                      25
Peru                         15
Czech Republic               11
Ukraine                      11
Serbia                       11
Macedonia                    10
Cyprus                       10
India                         8
Luxembourg                    6
Switzerland                   6
Armenia                       2
Bosnia and Herzegovina        2
Slovakia                      1
China                         1
Egypt                         1
Name: count, dtype: int64

In [ ]:
df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [ ]:
df.tail()

In [ ]:
df.head(8)

In [ ]:
df.tail(7)

In [ ]:
df['country'].isna().sum()

In [ ]:
df[['price','description']].isna().sum()

In [ ]:
df.dtypes

In [ ]:
df['points'].isna()

In [ ]:
df['points'].isna().sum()

In [ ]:
df['price'].isna()

In [ ]:
df['price'].isna().sum()

In [ ]:
df[['points','price']].isna()

In [ ]:
df[['points','price']].isna().sum()

In [ ]:
df['points'].median()

In [ ]:
df['price'].mean()

In [ ]:
df['price'].median()

In [ ]:
# checking how much memory a df is using

In [ ]:
df.memory_usage(deep=True)

In [ ]:
df.info()

In [ ]:
# 10.Generate descriptive statistics for numerical columns.

In [ ]:
country_grouped = df.groupby('country')

In [ ]:
country_grouped.mean(numeric_only=True)

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/winemag-data-130k-v2.csv')

In [ ]:
df

In [ ]:
# sorting values

In [ ]:
df.sort_values('price')

In [ ]:
import pandas as pd

In [ ]:
data = {
    'Store': ['North', 'South', 'North', 'West', 'South', 'North'],
    'Product': ['Apples', 'Oranges', 'Bananas', 'Apples', 'Bananas', 'Apples'],
    'Sales': [100, 150, 120, 80, 200, 90]
}

In [ ]:
data = {
    'Store': ['North', 'South', 'North', 'West', 'South', 'North'],
    'Product': ['Apples', 'Oranges', 'Bananas', 'Apples', 'Bananas', 'Apples'],
    'Sales': [100, 150, 120, 80, 200, 90]
}

In [ ]:
df

In [ ]:
grouped = df.groupby('Store')

In [ ]:
print(type(grouped))

In [ ]:
total_sales = df.groupby('Store')['Sales'].sum()

In [ ]:
print(total_sales)

In [ ]:
total_sales = df.groupby('Store')['Sales'].min()

In [ ]:
total_sales

In [ ]:
total_sales = df.groupby('Store')['Sales'].max()

In [ ]:
total_sales

In [ ]:
total_sales = df.groupby('Store')['Sales'].mean()

In [ ]:
total_sales

In [ ]:
total_sales = df.groupby('Store')['Sales'].count()

In [ ]:
total_sales

In [ ]:
total_sales = df.groupby('Store')['Sales'].median()

In [ ]:
total_sales

In [ ]:
total_sales = df.groupby('Store')['Sales'].std()

In [ ]:
total_sales

In [ ]:
import pandas as pd

In [ ]:
# Sample data: Names of people and their cities

In [ ]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'City': ['NY', 'LON', 'PAR', 'NYC']}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
# Create a mapping dictionary

In [ ]:
city_mapping = {
    'NY': 'New York',
    'NYC': 'New York',
    'LON': 'London',
    'PAR': 'Paris'
}

In [ ]:
# Apply map and save the result as a new column

In [ ]:
df['Full_City'] = df['City'].map(city_mapping)

In [ ]:
df

In [ ]:
# Create a mapping dictionary
city_mapping = {
    'NY': 'New York',
    'NYC': 'New York',
    'LON': 'London',
    'PAR': 'Paris'
}

# Apply map and save the result as a new column
df['Full_City'] = df['City'].map(city_mapping)

In [ ]:
df['Full_City']

In [ ]:
df['Name_Lower'] = df['Name'].map(lambda x: x.lower())

In [ ]:
df

In [ ]:
df['Name_Lower']

In [ ]:
# This ignores NaN values entirely during the mapping

In [ ]:
df['Full_City'] = df['City'].map(city_mapping, na_action='ignore')

In [ ]:
df['Full_City']

In [ ]:
#  When to use what?

# Use map() for substituting values in a single column (Series) using a dictionary or a function.
# Use apply() if you are running a custom function across entire rows or across a whole DataFrame along an axis.
# Use replace() if you only want to substitute specific items without converting missing items to NaN

In [ ]:
import pandas as pd

In [ ]:
# Visualization

# Pandas allows you to build data visualizations directly from DataFrame and Series objects by wrapping around the Matplotlib library.
#You can easily generate common statistical plots using the .plot() wrapper or its specialized sub-methods.

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
# 1. Create dummy structured data
data = {
    'Month': ['Jan', 'Feb', 'Mar', 'Apr'],
    'Sales': [1500, 2300, 1800, 3100],
    'Expenses': [1200, 1400, 1300, 1900]
}
df = pd.DataFrame(data)

In [ ]:
# 2. Generate the plot and add custom parameters
df.plot(x='Month', y=['Sales', 'Expenses'],
        kind='line', figsize=(8, 4),
        grid=True, title = 'Practicing maps')

In [ ]:
# Core Workflow Integration

# To visualize a Pandas DataFrame with Seaborn, you typically pass the DataFrame to the data parameter,
# and then assign the column names as strings to structural parameters like
# x, y, or hue.

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
# 2. Apply a Seaborn aesthetic theme
sns.set_theme(style='darkgrid')

In [ ]:
# 3. Create the plot mapping DataFrame columns directly
sns.scatterplot(data=df, x='total_bill', y='tip', hue='smoker')

In [ ]:
# 4. Display the plot
plt.show()

In [ ]:
# 3. Render the window frame display
plt.show()

In [ ]:
#Essential Customization Arguments
#The .plot() method supports many configuration arguments to clean up and design your charts directly inside the function call
#figsize: Controls dimensions via a tuple, e.g., figsize=(10, 6).
#title: Adds a main chart header string.
#xlabel / ylabel: Changes axis text labels.
#grid: Expects a boolean (True/False) to toggle background layout grids.
#subplots: When set to True, splits columns into individual charts instead of layering them together.

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
data = {
    'EmployeeID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Name': ['John', 'Mary', 'David','Sarah','James','Grace','Peter','Linda','Michael','Susan'],
    'Department': ['IT', 'HR', 'Finance','IT','Sales','HR','Finance','Sales','IT','HR'],
    'Age': [25, 30, 28, 35, 26, 32, 29, 31, 27, 34],
    'Salary': [50000, 65000, 60000, 80000, 55000, 70000, 62000, 68000, 58000,75000],
    'Experience': [2 ,5, 3, 8, 2, 6, 4, 5, 3, 7],

}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
# 2. Apply a Seaborn aesthetic theme
sns.set_theme(style='darkgrid')

In [ ]:
# 3. Create the plot mapping DataFrame columns directly
sns.scatterplot(data=df, x='Name', y='Age', hue='Department')

In [ ]:
#mappings

In [ ]:
import pandas as pd

In [ ]:
# Sample DataFrame
df = pd.DataFrame({'Gender': ['M', 'F', 'F', 'M', 'X']})

In [ ]:
# Define the map
gender_map = {'M': 'Male', 'F': 'Female'}

In [ ]:
# Apply mapping
df['Gender_Full'] = df['Gender'].map(gender_map)

In [ ]:
df

In [ ]:
# Convert text to lowercase using a lambda function
df['Gender_Lower'] = df['Gender'].map(lambda x: str(x).lower())

In [ ]:
df

In [ ]:
import pandas as pd

In [ ]:
# DISPLAY the first 5 rows of the dataframe to see wat it looks like
print('first 5 rows of the Dataframe')

In [ ]:
display(df.head())

In [ ]:
df.info()

In [ ]:
"""Filtering Data"""

# Filtering is a powerful technique to select a subset of your
# data based on one or more conditions. We use boolean indexing
# for this, which means we create a series of `True/False` values,
# and the DataFrame returns only the rows where the condition
# is `True`.

In [ ]:
# Let's filter the DataFrame to show only wines that come from
# 'Italy'.

In [ ]:
# Filter the DataFrame to show only wines from the US
#(now "United States") using isin)()

In [ ]:
us_wines = df[df['country'].isin(['US'])]

In [ ]:
df['country']

In [ ]:
us_wines

In [ ]:
us_wines.head()

In [ ]:
# Filter for wines from 'Italy' OR 'France'
 (now 'France(Europe)') using  isin()

In [ ]:
Italy_France_wines = df[df['country'].isin(['Italy','France'])]

In [ ]:
Italy_France_wines

In [ ]:
Italy_France_wines.head()

In [ ]:
print(f"First 5 rows of the filtered DataFrame:")
display(Italy_France_wines.head())

In [ ]:
print(f"Number of wines from Italy or France: {len(Italy_France_wines)}")

In [ ]:
import pandas as pd

In [ ]:
country_mapping = {
    'US': 'United States',
    'UK': 'United Kingdom',
    'Italy': 'Italy',
    'France': 'France(Europe)'
}

In [ ]:
import pandas as pd
df = pd.read_csv('/content/winemag-data-130k-v2.csv', on_bad_lines='skip', engine='python')

In [ ]:
df.head()

In [ ]:
country_mapping = {
    'US': 'United States',
    'UK': 'United Kingdom',
    'Italy': 'Italy',
    'France': 'France(Europe)'
}

In [ ]:
df['country'] = df['country']
.apply(lambda x: country_mapping.get(x, x))

In [ ]:
df['country']

In [ ]:
import pandas as pd
df = pd.read_csv('/content/winemag-data-130k-v2.csv')

In [ ]:
df.head()

In [ ]:

## Mapping is way to create new information from existing columns or
## to transform existing data. You can apply a function to each element in a
## series (a single column in a DatasFrame) to create new values.
## This is often done using the `.apply()` method or direct vectorized operations.

In [ ]:
df['country'].head()

In [ ]:
## Mapping is a new way to create new information from existing columns or
# to transform existing data. You can apply a function to each element in a
# series (a single column in a DataFrame) to create new values.
# This is often done using the .apply() method or direct vectorized operations.

In [ ]:
# Let's create a new column called `price_category` based on the `price`
# column. We'll categorize wines into 'Budget' (price < 20),
# 'Mid-Range' (20 <= price < 50), and 'Premium' (price => 50).

In [ ]:
df['country'].head(10)

In [ ]:
country_map = {
    "US" : "United States",
    "France" : "FR",
    "Italy" : "IT",
    "Spain": "SP"
}

In [ ]:
df["country_new"] = df["country"].map(country_map)

In [ ]:
df[["country","country_new"]].head(20)

In [ ]:
df["price_ngn"] = df["price"] * 1600

In [ ]:
df[["country","country_new","price","price_ngn"]]

In [ ]:
df[["price","price_ngn"]].head()

In [ ]:
# Suppose you want Expensive if price > 50
# Cheap otherwise

In [ ]:
df["category"] = df["price"]. map(lambda x : "Expensive" if x > 50 else "Cheap")

In [ ]:
df[["country_new","price","category"]].head(10)

In [ ]:
df["categorize_price"] = df["price"].map(lambda x: "Unknown" if pd.isna(x) else ("Budget"
                                                                                 if x < 20 else ("Mid-Range" if 20 <= x < 50 else "Premium")))

In [ ]:
df["categorize_price"]

In [ ]:
def categorize_price(price):
    if pd.isna(price):
        return "Unknown"
    elif price < 20:
        return "Budget"
    elif 20 <= price < 50:
        return "Mid-Range"
    else:
        return "Premium"
df["price_category"] = df["price"].apply(categorize_price)

In [ ]:
df["price_category"].head()

In [ ]:
df[["title", "price", "price_category"]].head()

In [ ]:
# Visualization

# Visualizatons are incredibly powerful for understanding your data. They can reveal insights that might be hidden in tables of numbers. For beginners, common types of visualizations include bar plots, histograms, and scatter plots.
# We'll use `matplotlib` and `Seaborn`  (which builds on `matplotlib` to create more attractive plots) to visualize the distribution of our `price_category`.

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Set a style for the plots(optional, but makes them look nicer)
sns.set_style("whitegrid")

In [ ]:
# Create a bar plot of the "price_category" distribution


plt.figure(figsize=(3, 6))
sns.countplot(data=df, x='price_category', order=['Budget', 'Mid-Range', 'Premium', 'Unknown'], palette='viridis', hue='price_category', legend=False)
plt.title('Distribution of Wine Price Categories')
plt.xlabel('Price Category')
plt.ylabel('Number of Wines')
plt.show()

In [ ]:
# Visualizing Relationships with Scatter Plots

# A scatter plot is useful for observing the relationship between
# `points` (wine quality) and `price`.

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Create a scatter plot of points vs price

plt.figure(figsize=(10,6))
sns.scatterplot(data=df, x='points', y='price', alpha=0.9, hue='price_category', palette='viridis')
plt.title('Wine Points vs Price')
plt.xlabel('Points')
plt.ylabel('Price')
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

In [ ]:
# Box Plot
# This shows:
# Median
# Minimun
# Maximum
# Outliers

# Useful for exploratory Data Analysis

In [ ]:
plt.figure(figsize=(8,5))
df[["price","points"]].boxplot()
plt.title("Price and Points Distrbution")
plt.show()

In [ ]:
price = df["price"].dropna()
plt.figure(figsize=(8,5))
plt.boxplot(price)
plt.title("Wine Price Boxplot")
plt.ylabel("Price")
plt.show()

In [ ]:
# Histogram
# How are wine prices distributed?
# This shows :
# Most wines are very Expensive

df["price"].hist()
plt.title("Wine Price Distribution")
plt.xlabel("Price")
plt.ylabel("Frequency")
plt.show()

In [ ]:
plt.figure(figsize=(10, 6))
sns.histplot(df['points'], bins=10, kde=True)
plt.title('Distribution of Wine Points')
plt.xlabel('Points')
plt.ylabel('Frequency')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

In [ ]:
# TAKE HOME(BOX PLOT)

plt.figure(figsize=(8,5))
df[["price","points"]].boxplot()
plt.title("Price and Points Distrbution")
plt.show()

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
plt.figure(figsize=(10,6))
df["points"].plot(kind='box')
plt.title("Wine Points Distribution")

plt.show()

In [ ]:
import pandas as pd
df = pd.read_csv("winemag-data-130k-v2.csv")

In [ ]:
df.head()

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Define the function to categorize price
def categorize_price(price):
    if pd.isna(price):
        return "Unknown"
    elif price < 20:
        return "Budget"
    elif 20 <= price < 50:
        return "Mid-Range"
    else:
        return "Premium"

# Apply the function to create the 'price_category' column
df["price_category"] = df["price"].apply(categorize_price)

# Create a scatter plot of points vs price
plt.figure(figsize=(10,6))
sns.scatterplot(data=df, x='points', y='price', alpha=0.9, hue='price_category', palette='viridis')
plt.title('Wine Points vs Price')
plt.xlabel('Points')
plt.ylabel('Price')
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(10,6))
sns.scatterplot(data=df, x='country', y='price', alpha=0.9, palette='viridis')
plt.title('Country VS Price')
plt.xlabel('Country')
plt.ylabel('Price')
plt.show()

In [ ]:
# Create a bar plot of the "price_category" distribution

plt.figure(figsize=(3, 6))
sns.countplot(data=df, x='price_category', order=['Budget', 'Mid-Range', 'Premium', 'Unknown'], palette='viridis', hue='price_category', legend=False)
plt.title('Distribution of Wine Price Categories')
plt.xlabel('Price Category')
plt.ylabel('Number of Wines')
plt.show()

In [ ]:
# Create a bar plot of the 'country' distribution

plt.figure(figsize=(8, 6))
sns.countplot(data=df, x='country', palette='viridis', hue='country', legend=False)
plt.title('Distribution of Wines by Country')
plt.xlabel('Country')
plt.ylabel('Number of Wines')
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Bar chart for 'country' (showing top 10 countries for readability)
plt.figure(figsize=(12, 6))
top_countries = df['country'].value_counts().nlargest(10).index
sns.countplot(data=df[df['country'].isin(top_countries)], x='country', order=top_countries, palette='viridis')
plt.title('Top 10 Countries by Number of Wines')
plt.xlabel('Country')
plt.ylabel('Number of Wines')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# Histogram for 'price'
plt.figure(figsize=(10, 6))
sns.histplot(df['price'].dropna(), bins=30, kde=True, color='skyblue')
plt.title('Distribution of Wine Prices')
plt.xlabel('Price')
plt.ylabel('Frequency')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# Bar chart for 'winery' (showing top 10 wineries for readability)
plt.figure(figsize=(12, 6))
top_wineries = df['winery'].value_counts().nlargest(10).index
sns.countplot(data=df[df['winery'].isin(top_wineries)], x='winery', order=top_wineries, palette='magma')
plt.title('Top 10 Wineries by Number of Wines')
plt.xlabel('Winery')
plt.ylabel('Number of Wines')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

In [ ]:
# Groupy and agregation

# What is Groupby()?

# Groupby is used to:
# Split the same data into groups.
# Apply some calculations on each grouo.
# Combine results

# It follows the idea:

# Split-> Apply -> Combine